<?php

/**
 * @file
 * General functions relating to this module.
 * This file will not include the searches themselves.
 */
require_once 'includes/GermplasmAccessionSearch.inc';
require_once 'includes/TraitSearch.inc';
require_once 'includes/GeneticMapSearch.inc';
require_once 'includes/form_elements.inc';
require_once 'includes/mviews.inc';

/**
 * Implement hook_chado_custom_search().
 *
 * This hook simply lists the machine name of the searches so that we can find
 * the info hook. We've done this for performance reasons.
 */
function divseek_search_chado_custom_search() {
  $searches = [];

  $searches['GermplasmAccessionSearch'] = 'Germplasm Accessions';
  $searches['TraitSearch'] = 'Phenotypic Traits';
  $searches['GeneticMapSearch'] = 'Genetic Maps';

  return $searches;
}

function divseek_search_theme() {
  return array(
    'divseek_search_inline_form_element' => array(
      'render element' => 'element',
    ),
  );
}

function divseek_search_flush_caches() {
  divseek_search_mview_phenotype_means();
}
